spring.application.name=fintechApp
spring.main.banner-mode=OFF
logging.file.name=mcp-server.log
logging.pattern.console=
spring.ai.mcp.server.name=mcpFintechBank_api_inventory_server
spring.ai.mcp.server.version=1.0.0
